jobs:
  - script: >
      freeStyleJob('seed-job') {
        triggers {
          hudsonStartupTrigger {
            quietPeriod("10")
            runOnChoice("ON_CONNECT")
            label("")
            nodeParameterName('master')
          }
        }
        if( !System.getenv('DOCKER_COMPOSE') ) {
          scm {
            git {
              remote {
                url('https://github.com/aamirshehzad111/infohub-jenkins.git')
                credentials('aamirshehzad111')
              }
              branches('master')
            }
          }
        }
        displayName('seed-job')
        steps {
          dsl {
            external('jenkins/jobs/folder_view/*.groovy', 'jenkins/jobs/*.groovy')
            removeAction('DELETE')
            removeViewAction('DELETE')
          }
        }
        publishers {
          downstreamParameterized {
            trigger('common-jobs/seed_sharedlib') {
              condition('SUCCESS')
            }
          }
        }
      }
